-- Generated by pgdesigner test data generator
-- Seed: 42

BEGIN;

-- Table: "categories" (5 rows)
INSERT INTO "categories" ("id", "parent_id", "name", "slug", "description", "sort_order", "created_at") OVERRIDING SYSTEM VALUE VALUES
  (1, NULL, 'his painting', 'been-outside', 'Map the happy path through person. Ruthlessly remove dead week. Review the day every 4 weeks. Launch the week midweek for clarity. Launch the child midweek for clarity.', 1, '2022-01-25 01:09:10'),
  (2, 1, 'cute goodness', 'ourselves-since', 'Instrument the number for observability. Surface risks around the government least. Onward to better work! Mind the child, then celebrate! Choose friendly defaults.', 2, '2023-06-11 23:30:55'),
  (3, 2, 'motionless shower', 'significant-pack', 'Sample point at 58s intervals. Prefer predictable hand over surprising woman. Raise contrast where the fact hides. The brilliance might be cute most.', NULL, '2022-05-30 18:20:40'),
  (4, 1, 'precious luck', 'then-bathe', 'Review the week every 4 weeks. Protect the company under lucky load. Continuously measure the company and intimidate the outliers. Choose foolish defaults.', 4, '2025-01-09 20:58:47'),
  (5, 2, 'those microscope', 'were-remove', 'Budget latency for person. Moreover, I ring the government. About the life, we highlight a smaller fact. Choose prickling defaults.', 5, '2022-03-23 10:57:44');

-- Table: "tags" (5 rows)
INSERT INTO "tags" ("id", "name", "color") OVERRIDING SYSTEM VALUE VALUES
  (1, 'empty philosophy', '#ce2ae4'),
  (2, 'Taiwanese weather', NULL),
  (3, 'sufficient gang', NULL),
  (4, 'anything bale', '#3cf1aa'),
  (5, 'their hat', '#b479f6');

-- Table: "users" (5 rows)
INSERT INTO "users" ("id", "email", "display_name", "role", "settings", "tags", "search_vector", "is_active", "created_at", "updated_at") OVERRIDING SYSTEM VALUE VALUES
  (1, 'geoffreysutton@wells.org', 'Leilani Lindgren', 'editor', '{"key_1": "wisp"}', ARRAY['late', 'these', 'juicer'], NULL, false, '2024-01-09 13:21:25', '2024-01-18 06:21:25'),
  (2, 'tomashowell@weber.name', 'Lexie Sanchez', 'owner', '{"key_2": "these"}', ARRAY['infrequently'], NULL, false, '2020-05-27 23:49:05', '2020-05-28 19:49:05'),
  (3, 'malachiosinski@cooper.biz', 'Nina Satterfield', 'editor', '{"key_3": "that"}', ARRAY['late', 'onto', 'why'], NULL, false, '2021-12-27 23:17:03', '2022-01-04 23:17:03'),
  (4, 'jeangrant@stark.io', 'Glenda Webb', 'editor', '{"key_4": "Taiwanese"}', ARRAY['this'], NULL, true, '2024-04-21 10:02:11', '2024-05-01 09:02:11'),
  (5, 'madieyang@fisher.net', 'Dereck Rath', 'owner', '{"key_5": "in"}', ARRAY['you'], NULL, false, '2020-09-18 06:10:39', '2020-09-23 05:10:39');

-- Table: "audit_log" (5 rows)
INSERT INTO "audit_log" ("id", "user_id", "table_name", "record_id", "action", "old_data", "new_data", "ip_address", "created_at") OVERRIDING SYSTEM VALUE VALUES
  (1, 4, 'few pain', 56026, 'DELETE', '{"key_1": "crowd"}', '{"key_1": "buy"}', '76.6.126.163', '2020-10-12 01:32:46'),
  (2, 5, 'your gas station', 65990, 'UPDATE', '{"key_2": "catalog"}', '{"key_2": "result"}', '170.191.146.152', '2023-08-03 11:33:41'),
  (3, 5, 'few work', 88391, 'UPDATE', NULL, '{"key_3": "murder"}', '57.67.178.233', '2024-01-30 22:46:14'),
  (4, 4, 'anxious minute', 5860, 'UPDATE', '{"key_4": "other"}', '{"key_4": "climb"}', '151.144.101.137', '2022-04-21 21:33:05'),
  (5, 2, 'each bevy', 62247, 'DELETE', '{"key_5": "our"}', '{"key_5": "ostrich"}', '223.8.109.209', '2022-11-18 10:53:21');

-- Table: "booking_slots" (5 rows)
INSERT INTO "booking_slots" ("id", "room_name", "booked_during", "booked_by") OVERRIDING SYSTEM VALUE VALUES
  (1, 'inquiring thing', '[2016-07-06 04:09:59,2016-07-07 19:09:59)', 3),
  (2, 'Lincolnian army', '[1989-05-14 02:27:08,1989-05-14 22:27:08)', 4),
  (3, 'his wad', '[1989-08-26 18:19:05,1989-08-27 03:19:05)', 3),
  (4, 'each bell', '[1963-12-29 04:12:10,1963-12-30 22:12:10)', 3),
  (5, 'their eye', '[1984-04-12 12:06:06,1984-04-13 12:06:06)', 1);

-- Table: "documents" (5 rows)
INSERT INTO "documents" ("id", "category_id", "author_id", "title", "body", "metadata", "tags", "status", "version", "search_vector", "published_at", "created_at", "updated_at") OVERRIDING SYSTEM VALUE VALUES
  (1, 2, 2, 'Celebrate wins tied to the place.', 'Celebrate wins tied to the case. Share the decision record for the year. Sometimes the eye gallop rarely. Defaults at Scale Unlimited have shape case. Remove first friction from the man.', '{"key_1": "so"}', ARRAY['her'], 'review', 4624, NULL, '2022-03-29 11:39:55', '2024-01-12 07:42:05', '2024-02-09 13:42:05'),
  (2, 1, 4, 'As clap quickly repel the group.', 'Clarify ownership of the part earlier. Mornings in San Diego favor thing. Rate-limit part by default.', '{"key_2": "whatever"}', ARRAY['bale', 'covey', 'it'], 'published', 6722, NULL, '2023-06-13 10:06:03', '2025-01-02 04:32:44', '2025-01-17 08:32:44'),
  (3, 5, 1, 'Design for failure and graceful work.', 'Whom dance quickly watch the work. Draw a diagram for the year so.', '{"key_3": "upon"}', ARRAY['lately', 'as'], 'draft', 3068, NULL, '2024-02-16 18:10:05', '2025-08-21 08:28:51', '2025-09-01 20:28:51'),
  (4, 3, 3, 'Remove first friction from the problem.', 'Review the child every 1 weeks. Explicitly name the man before you persuade it.', '{"key_4": "consequently"}', ARRAY['move'], 'review', 5152, NULL, '2024-09-26 21:47:17', '2023-08-11 18:24:53', '2023-09-06 08:24:53'),
  (5, 3, 4, 'Remove first friction from the thing.', 'Defaults at Civic Impulse LLC had shape way. Guard number with sensible limits. Stage eye behind feature flags.', '{"key_5": "for"}', ARRAY['with', 'luxuty', 'Alaskan'], 'review', 72, NULL, '2022-01-14 08:54:14', '2025-10-21 02:46:46', '2025-10-28 05:46:46');

-- Table: "document_permissions" (5 rows)
INSERT INTO "document_permissions" ("id", "document_id", "user_id", "role", "granted_at", "expires_at") OVERRIDING SYSTEM VALUE VALUES
  (1, 4, 5, 'editor', '2025-07-31 18:50:31', '2026-04-06 21:50:31'),
  (2, 2, 5, 'admin', '2021-04-30 03:44:02', '2022-01-10 05:44:02'),
  (3, 4, 2, 'viewer', '2020-03-23 19:33:17', '2020-09-28 07:33:17'),
  (4, 5, 1, 'owner', '2021-10-01 22:50:18', '2022-06-25 20:50:18'),
  (5, 2, 4, 'viewer', '2020-10-20 18:34:10', '2021-05-16 15:34:10');

-- Table: "document_tags" (5 rows)
INSERT INTO "document_tags" ("document_id", "tag_id") VALUES
  (3, 4),
  (1, 5),
  (1, 2),
  (4, 5),
  (3, 2);

COMMIT;
